// dashboard/src/views/LiveLogs.vue
<template>
  <div class="bw-page">
    <div class="bw-page-header">
      <div>
        <h1>Live Logs</h1>
        <p class="subtitle">Real-time application logs</p>
      </div>
      <Button icon="pi pi-refresh" label="Refresh" class="p-button-outlined p-button-sm" :loading="loading" @click="loadLogs" />
    </div>

    <!-- Toolbar -->
    <div class="bw-section toolbar-section">
      <div class="bw-section-body">
        <div class="toolbar-row">
          <div class="toolbar-field">
            <label>Source</label>
            <Dropdown v-model="source" :options="sourceOptions" optionLabel="label" optionValue="value" class="p-dropdown-sm" />
          </div>
          <div class="toolbar-field">
            <label>Level</label>
            <Dropdown v-model="level" :options="levelOptions" optionLabel="label" optionValue="value" class="p-dropdown-sm" />
          </div>
          <div class="toolbar-field">
            <label>Limit</label>
            <InputNumber v-model="limit" :min="20" :max="1000" :step="20" class="p-inputtext-sm limit-input" />
          </div>
          <div class="toolbar-field switch-field">
            <InputSwitch v-model="autoRefresh" />
            <label>Auto-refresh</label>
          </div>
        </div>
      </div>
    </div>

    <!-- Logs -->
    <div class="bw-section">
      <div class="bw-section-header">
        <span class="log-meta">{{ logs.length }} entries</span>
        <span v-if="lastUpdated" class="log-meta">Updated {{ lastUpdated }}</span>
      </div>
      <div class="log-console">
        <div v-if="logs.length === 0" class="log-empty">No logs found for selected filters.</div>
        <div v-for="log in logs" :key="log.id" class="log-line" :class="`level-${(log.level || 'INFO').toLowerCase()}`">
          <span class="log-ts">[{{ formatTime(log.timestamp) }}]</span>
          <span class="log-src">[{{ log.source || log.logger || 'app' }}]</span>
          <span class="log-lvl">[{{ log.level }}]</span>
          <span class="log-msg">{{ log.message }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { api } from '@/services/api'
import type { LogEntry } from '@/types'
import Button from 'primevue/button'
import Dropdown from 'primevue/dropdown'
import InputNumber from 'primevue/inputnumber'
import InputSwitch from 'primevue/inputswitch'

const logs = ref<LogEntry[]>([])
const loading = ref(false)
const source = ref('all')
const level = ref('')
const limit = ref(200)
const autoRefresh = ref(true)
const lastUpdated = ref('')
let timer: number | null = null

const sourceOptions = [
  { label: 'All', value: 'all' },
  { label: 'Gateway', value: 'gateway' },
  { label: 'Service', value: 'service' },
  { label: 'FastAPI', value: 'fastapi' },
  { label: 'Baileys', value: 'baileys' },
]

const levelOptions = [
  { label: 'All', value: '' },
  { label: 'DEBUG', value: 'DEBUG' },
  { label: 'INFO', value: 'INFO' },
  { label: 'WARNING', value: 'WARNING' },
  { label: 'ERROR', value: 'ERROR' },
  { label: 'CRITICAL', value: 'CRITICAL' },
]

const formatTime = (iso: string) => {
  if (!iso) return '-'
  const dt = new Date(iso)
  return Number.isNaN(dt.getTime()) ? iso : dt.toLocaleString()
}

const loadLogs = async () => {
  loading.value = true
  try {
    logs.value = await api.getLogs(level.value || undefined, limit.value, source.value)
    lastUpdated.value = new Date().toLocaleTimeString()
  } catch (error) {
    console.error('Failed to load logs', error)
  } finally {
    loading.value = false
  }
}

const startAutoRefresh = () => {
  if (timer) window.clearInterval(timer)
  if (!autoRefresh.value) return
  timer = window.setInterval(loadLogs, 5000)
}

watch(autoRefresh, startAutoRefresh)
watch([source, level, limit], loadLogs)

onMounted(async () => { await loadLogs(); startAutoRefresh() })
onBeforeUnmount(() => { if (timer) window.clearInterval(timer) })
</script>

<style scoped>
.toolbar-section { margin-bottom: var(--bw-space-lg); }

.toolbar-row {
  display: flex;
  align-items: flex-end;
  gap: var(--bw-space-md);
  flex-wrap: wrap;
}

.toolbar-field {
  display: flex;
  flex-direction: column;
  gap: 0.3rem;
}

.toolbar-field label {
  font-size: 0.72rem;
  color: var(--bw-text-muted);
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.switch-field {
  flex-direction: row;
  align-items: center;
  gap: var(--bw-space-sm);
  margin-bottom: 0.2rem;
}

.switch-field label {
  text-transform: none;
  font-size: 0.82rem;
  font-weight: 500;
  color: var(--bw-text-secondary);
}

.limit-input { width: 100px; }

.log-meta {
  font-size: 0.75rem;
  color: var(--bw-text-muted);
}

/* Log console */
.log-console {
  background: #070e1a;
  border-top: 1px solid var(--bw-border-subtle);
  padding: 0.6rem 1rem;
  max-height: 65vh;
  overflow: auto;
  font-family: var(--bw-font-mono);
  font-size: 0.78rem;
  line-height: 1.7;
}

.log-line {
  padding: 0.1rem 0.25rem;
  border-radius: 2px;
  color: #d1ddf0;
  transition: background var(--bw-transition-fast);
}

.log-line:hover {
  background: rgba(148, 163, 184, 0.06);
}

.log-empty {
  color: var(--bw-text-muted);
  padding: 0.5rem 0;
}

.log-ts { color: #7191b5; }
.log-src { color: #6cc9b3; }
.log-lvl { color: #a3c4f5; }

.level-error .log-lvl,
.level-critical .log-lvl { color: #ff8e8e; }
.level-error .log-msg,
.level-critical .log-msg { color: #ffc4c4; }

.level-warning .log-lvl { color: #ffd487; }
</style>

// dashboard-react/src/pages/LiveLogs.tsx
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import {
  FileText,
  RefreshCw,
  Filter,
  AlertTriangle,
  Info,
  AlertCircle,
  Bug,
} from 'lucide-react';
import { api } from '../services/api';
import { LoadingState } from '../components/ui/LoadingState';
import { REFETCH_INTERVALS, LIMITS } from '../constants';
import type { LogEntry } from '../types';

const levels = [
  { value: '', label: 'All Levels' },
  { value: 'DEBUG', label: 'Debug' },
  { value: 'INFO', label: 'Info' },
  { value: 'WARNING', label: 'Warning' },
  { value: 'ERROR', label: 'Error' },
];

const sources = [
  { value: '', label: 'All Sources' },
  { value: 'fastapi', label: 'FastAPI' },
  { value: 'baileys', label: 'Baileys' },
  { value: 'system', label: 'System' },
  { value: 'gateway', label: 'Gateway' },
];

export function LiveLogs() {
  const [level, setLevel] = useState('');
  const [source, setSource] = useState('');
  const [autoRefresh, setAutoRefresh] = useState(true);

  const { data: logs, isLoading, refetch } = useQuery({
    queryKey: ['logs', level, source],
    queryFn: () => api.getLogs({ level: level || undefined, source: source || undefined, limit: LIMITS.MAX_LOGS }),
    refetchInterval: autoRefresh ? REFETCH_INTERVALS.LIVE_LOGS : false,
  });

  const getLevelIcon = (level: string) => {
    switch (level) {
      case 'ERROR':
        return <AlertCircle className="w-3.5 h-3.5" style={{ color: 'var(--danger)' }} />;
      case 'WARNING':
        return <AlertTriangle className="w-3.5 h-3.5" style={{ color: 'var(--warning)' }} />;
      case 'DEBUG':
        return <Bug className="w-3.5 h-3.5" style={{ color: 'var(--info)' }} />;
      default:
        return <Info className="w-3.5 h-3.5" style={{ color: 'var(--brand-accent)' }} />;
    }
  };

  const getLevelStyle = (level: string) => {
    switch (level) {
      case 'ERROR':
        return { bg: 'var(--danger-soft)', color: 'var(--danger)', border: 'var(--danger-soft-border)' };
      case 'WARNING':
        return { bg: 'var(--warning-soft)', color: 'var(--warning)', border: 'var(--warning-soft-border)' };
      case 'DEBUG':
        return { bg: 'var(--info-soft)', color: 'var(--info)', border: 'var(--info-soft-border)' };
      default:
        return { bg: 'var(--brand-soft)', color: 'var(--brand-accent)', border: 'var(--brand-soft-border)' };
    }
  };

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>
            Live Logs
          </h2>
          <p className="text-sm mt-0.5" style={{ color: 'var(--text-tertiary)' }}>
            Real-time application logs and events
          </p>
        </div>
        <div className="flex items-center gap-2">
          <label className="flex items-center gap-2 cursor-pointer">
            <button
              onClick={() => setAutoRefresh(!autoRefresh)}
              className={`toggle ${autoRefresh ? 'active' : ''}`}
              role="switch"
              aria-checked={autoRefresh}
              aria-label="Enable automatic refresh"
            />
            <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>Auto</span>
          </label>

          <button onClick={() => refetch()} className="btn-secondary">
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
        </div>
      </div>

      {/* Filters */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        className="card p-4"
      >
        <div className="flex items-center gap-3 flex-wrap">
          <div className="flex items-center gap-1.5">
            <Filter className="w-3.5 h-3.5" style={{ color: 'var(--text-tertiary)' }} />
            <span className="text-xs font-medium" style={{ color: 'var(--text-tertiary)' }}>Filters:</span>
          </div>

          <select
            value={level}
            onChange={(e) => setLevel(e.target.value)}
            className="input w-auto text-xs"
            aria-label="Filter by log level"
          >
            {levels.map((l) => (
              <option key={l.value} value={l.value}>{l.label}</option>
            ))}
          </select>

          <select
            value={source}
            onChange={(e) => setSource(e.target.value)}
            className="input w-auto text-xs"
            aria-label="Filter by log source"
          >
            {sources.map((s) => (
              <option key={s.value} value={s.value}>{s.label}</option>
            ))}
          </select>
        </div>
      </motion.div>

      {/* Logs */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="card overflow-hidden"
      >
        <div className="max-h-[600px] overflow-y-auto">
          {isLoading ? (
            <div className="py-12">
              <LoadingState size="md" />
            </div>
          ) : (
            <div>
              {logs?.logs?.map((log: LogEntry) => {
                const ls = getLevelStyle(log.level);
                return (
                  <div
                    key={log.id}
                    className="px-4 py-3 transition-colors"
                    style={{ borderBottom: '1px solid var(--border-subtle)' }}
                    onMouseEnter={(e) => (e.currentTarget.style.background = 'var(--bg-input)')}
                    onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
                  >
                    <div className="flex items-start gap-3">
                      <div className="flex-shrink-0 mt-0.5">
                        {getLevelIcon(log.level)}
                      </div>

                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-0.5">
                          <span
                            className="px-1.5 py-0.5 text-[10px] font-semibold rounded"
                            style={{
                              background: ls.bg,
                              color: ls.color,
                              border: `1px solid ${ls.border}`,
                            }}
                          >
                            {log.level}
                          </span>

                          <span className="text-[10px]" style={{ color: 'var(--text-tertiary)' }}>
                            {new Date(log.timestamp).toLocaleString()}
                          </span>

                          {log.source && (
                            <span className="text-[10px]" style={{ color: 'var(--text-tertiary)' }}>
                              [{log.source}]
                            </span>
                          )}
                        </div>

                        <p className="text-xs font-mono" style={{ color: 'var(--text-tertiary)' }}>
                          {log.logger}
                        </p>
                        <p className="text-sm mt-0.5" style={{ color: 'var(--text-primary)' }}>
                          {log.message}
                        </p>
                      </div>
                    </div>
                  </div>
                );
              })}

              {logs?.logs?.length === 0 && (
                <div className="py-12 text-center" style={{ color: 'var(--text-tertiary)' }}>
                  <div className="flex flex-col items-center gap-2">
                    <FileText className="w-10 h-10 opacity-40" />
                    <p className="text-sm">No logs found</p>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}
