// dashboard/src/views/SystemControl.vue
<template>
  <div class="bw-page">
    <div class="bw-page-header">
      <div>
        <h1>System Control</h1>
        <p class="subtitle">Monitor and manage services</p>
      </div>
      <Button label="Refresh" icon="pi pi-refresh" class="p-button-outlined p-button-sm" :loading="loading" @click="loadStatus" />
    </div>

    <!-- Status + Resources -->
    <div class="system-grid">
      <div class="bw-section">
        <div class="bw-section-header">
          <h2><i class="pi pi-check-circle"></i> Service Status</h2>
        </div>
        <div class="bw-section-body">
          <div class="status-list">
            <div class="status-row">
              <div class="status-left">
                <span class="bw-status-dot" :class="whatsappConnected ? 'bw-status-dot--online' : 'bw-status-dot--offline'"></span>
                <span>WhatsApp Session</span>
              </div>
              <Tag :value="whatsappConnected ? 'Connected' : 'Disconnected'" :severity="whatsappConnected ? 'success' : 'danger'" />
            </div>
            <div class="status-row">
              <div class="status-left">
                <span class="bw-status-dot" :class="queueRunning ? 'bw-status-dot--online' : 'bw-status-dot--warning'"></span>
                <span>Queue Worker</span>
              </div>
              <Tag :value="queueRunning ? 'Running' : 'Stopped'" :severity="queueRunning ? 'success' : 'warning'" />
            </div>
            <div class="status-row">
              <div class="status-left">
                <span class="bw-status-dot" :class="dbConnected ? 'bw-status-dot--online' : 'bw-status-dot--offline'"></span>
                <span>Database</span>
              </div>
              <Tag :value="dbConnected ? 'Connected' : 'Disconnected'" :severity="dbConnected ? 'success' : 'danger'" />
            </div>
          </div>
        </div>
      </div>

      <div class="bw-section">
        <div class="bw-section-header">
          <h2><i class="pi pi-chart-bar"></i> Resources</h2>
        </div>
        <div class="bw-section-body">
          <div class="resource-list">
            <div class="resource-row">
              <span class="resource-label">CPU</span>
              <div class="resource-bar-wrap">
                <ProgressBar :value="resources?.cpu_percent ?? 0" :showValue="false" class="resource-bar" />
              </div>
              <span class="resource-pct">{{ resources?.cpu_percent ?? 0 }}%</span>
            </div>
            <div class="resource-row">
              <span class="resource-label">Memory</span>
              <div class="resource-bar-wrap">
                <ProgressBar :value="resources?.memory?.percent ?? 0" :showValue="false" class="resource-bar" />
              </div>
              <span class="resource-pct">{{ resources?.memory?.percent ?? 0 }}%</span>
            </div>
            <div class="resource-row">
              <span class="resource-label">Disk</span>
              <div class="resource-bar-wrap">
                <ProgressBar :value="resources?.disk?.percent ?? 0" :showValue="false" class="resource-bar" />
              </div>
              <span class="resource-pct">{{ resources?.disk?.percent ?? 0 }}%</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Actions -->
    <div class="bw-section">
      <div class="bw-section-header">
        <h2><i class="pi pi-bolt"></i> Actions</h2>
      </div>
      <div class="bw-section-body">
        <div class="actions-grid">
          <Button label="Restart Baileys" icon="pi pi-sync" severity="contrast" class="p-button-sm" :loading="actionLoading === 'restart'" @click="restartBaileys" />
          <Button label="Disconnect WhatsApp" icon="pi pi-sign-out" severity="warning" class="p-button-sm" :loading="actionLoading === 'disconnect'" @click="disconnectWhatsApp" />
          <Button label="Clear Session" icon="pi pi-trash" severity="danger" class="p-button-sm" :loading="actionLoading === 'clear'" @click="clearSession" />
          <Button v-if="!queueRunning" label="Start Queue" icon="pi pi-play" severity="success" class="p-button-sm" :loading="actionLoading === 'queue-start'" @click="startQueueWorker" />
          <Button v-else label="Stop Queue" icon="pi pi-stop" severity="secondary" class="p-button-sm" :loading="actionLoading === 'queue-stop'" @click="stopQueueWorker" />
          <Button label="Process Now" icon="pi pi-send" severity="info" class="p-button-sm" :loading="actionLoading === 'queue-process'" @click="processQueueNow" />
        </div>
        <p v-if="message" class="action-message">{{ message }}</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api } from '@/services/api'
import Button from 'primevue/button'
import Tag from 'primevue/tag'
import ProgressBar from 'primevue/progressbar'
import type { DashboardStats, QueueStats, SystemResources } from '@/types'

const loading = ref(false)
const actionLoading = ref('')
const message = ref('')
const stats = ref<DashboardStats | null>(null)
const queueStats = ref<QueueStats | null>(null)
const resources = ref<SystemResources | null>(null)

const whatsappConnected = computed(() => stats.value?.whatsapp?.state === 'connected')
const queueRunning = computed(() => Boolean(queueStats.value?.worker_running))
const dbConnected = computed(() => Boolean(stats.value?.database_connected))

const loadStatus = async () => {
  loading.value = true
  try {
    const [s, q, r] = await Promise.all([api.getDashboardStats(), api.getQueueStats(), api.getSystemResources()])
    stats.value = s; queueStats.value = q; resources.value = r
  } catch { message.value = 'Failed to refresh.' } finally { loading.value = false }
}

const runAction = async (key: string, action: () => Promise<{ message?: string }>) => {
  actionLoading.value = key; message.value = ''
  try {
    const result = await action()
    message.value = result.message || 'Done.'
    await loadStatus()
  } catch (e: any) {
    message.value = e?.message || 'Action failed.'
  } finally { actionLoading.value = '' }
}

const restartBaileys = () => runAction('restart', () => api.restartBaileys())
const disconnectWhatsApp = () => runAction('disconnect', () => api.disconnectWhatsApp())
const clearSession = () => runAction('clear', () => api.clearWhatsAppSession())
const startQueueWorker = () => runAction('queue-start', () => api.startQueueWorker())
const stopQueueWorker = () => runAction('queue-stop', () => api.stopQueueWorker())
const processQueueNow = () => runAction('queue-process', () => api.processQueueNow(25))

onMounted(loadStatus)
</script>

<style scoped>
.system-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--bw-space-lg);
  margin-bottom: var(--bw-space-lg);
}

@media (max-width: 900px) {
  .system-grid { grid-template-columns: 1fr; }
}

/* Status list */
.status-list {
  display: flex;
  flex-direction: column;
}

.status-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--bw-border-subtle);
}

.status-row:last-child { border-bottom: none; }

.status-left {
  display: flex;
  align-items: center;
  gap: var(--bw-space-sm);
  font-size: 0.875rem;
  font-weight: 500;
}

/* Resources */
.resource-list {
  display: flex;
  flex-direction: column;
  gap: var(--bw-space-md);
}

.resource-row {
  display: flex;
  align-items: center;
  gap: var(--bw-space-md);
}

.resource-label {
  font-size: 0.82rem;
  color: var(--bw-text-secondary);
  font-weight: 500;
  min-width: 55px;
}

.resource-bar-wrap {
  flex: 1;
}

.resource-bar {
  height: 6px !important;
}

.resource-pct {
  font-size: 0.82rem;
  font-weight: 600;
  color: var(--bw-text-primary);
  min-width: 36px;
  text-align: right;
}

/* Actions */
.actions-grid {
  display: flex;
  flex-wrap: wrap;
  gap: var(--bw-space-sm);
}

.action-message {
  margin-top: var(--bw-space-md);
  font-size: 0.82rem;
  color: var(--bw-text-secondary);
}
</style>

// dashboard-react/src/pages/SystemControl.tsx
import { useState, useCallback } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { toast } from 'sonner';
import {
  Cpu,
  HardDrive,
  MemoryStick,
  RefreshCw,
  Play,
  Square,
  Loader2,
  Server,
  Activity,
} from 'lucide-react';
import { api } from '../services/api';
import { useDashboardStore } from '../stores/dashboardStore';
import { LoadingState } from '../components/ui/LoadingState';
import { formatBytes } from '../utils/formatters';
import { REFETCH_INTERVALS } from '../constants';

function ProgressBar({ value, color }: { value: number; color: string }) {
  return (
    <div className="h-2 rounded-full overflow-hidden" style={{ background: 'var(--bg-input)' }}>
      <div
        className="h-full rounded-full transition-all duration-500"
        style={{ width: `${Math.min(value, 100)}%`, background: color }}
      />
    </div>
  );
}

function getBarColor(percent: number): string {
  if (percent > 80) return 'var(--danger)';
  if (percent > 60) return 'var(--warning)';
  return 'var(--success)';
}

export function SystemControl() {
  const queryClient = useQueryClient();
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const version = useDashboardStore(state => state.stats?.system.version) || '0.0.0';

  const { data: resources, isLoading } = useQuery({
    queryKey: ['system-resources'],
    queryFn: () => api.getSystemResources(),
    refetchInterval: REFETCH_INTERVALS.QUEUE_STATS,
  });

  const startQueueMutation = useMutation({
    mutationFn: () => api.startQueueWorker(),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['queue-messages'] });
      toast.success('Queue worker started successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to start queue worker: ${error.message}`);
    },
  });

  const stopQueueMutation = useMutation({
    mutationFn: () => api.stopQueueWorker(),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['queue-messages'] });
      toast.success('Queue worker stopped successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to stop queue worker: ${error.message}`);
    },
  });

  const restartBaileysMutation = useMutation({
    mutationFn: () => api.restartBaileys(),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['baileys-status'] });
      toast.success('Baileys service restarted successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to restart Baileys: ${error.message}`);
    },
  });

  const handleAction = useCallback(async (
    action: string,
    mutation: { mutateAsync: () => Promise<unknown> }
  ) => {
    setActionLoading(action);
    await mutation.mutateAsync();
    setActionLoading(null);
  }, []);

  if (isLoading) {
    return <LoadingState size="lg" fullPage />;
  }

  const cpuPercent = resources?.cpu_percent ?? 0;
  const memPercent = resources?.memory?.percent ?? 0;
  const diskPercent = resources?.disk?.percent ?? 0;

  const resourceCards = [
    {
      label: 'CPU Usage',
      value: `${cpuPercent.toFixed(1)}%`,
      percent: cpuPercent,
      icon: Cpu,
      iconBg: 'var(--info-soft)',
      iconColor: 'var(--info)',
    },
    {
      label: 'Memory Usage',
      value: `${memPercent.toFixed(1)}%`,
      percent: memPercent,
      icon: MemoryStick,
      iconBg: 'var(--brand-soft)',
      iconColor: 'var(--brand-accent)',
      detail: `${formatBytes(resources?.memory.used || 0)} / ${formatBytes(resources?.memory.total || 0)}`,
    },
    {
      label: 'Disk Usage',
      value: `${diskPercent.toFixed(1)}%`,
      percent: diskPercent,
      icon: HardDrive,
      iconBg: 'var(--warning-soft)',
      iconColor: 'var(--warning)',
      detail: `${formatBytes(resources?.disk?.used ?? 0)} / ${formatBytes(resources?.disk?.total ?? 0)}`,
    },
  ];

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>
            System
          </h2>
          <p className="text-sm mt-0.5" style={{ color: 'var(--text-tertiary)' }}>
            Monitor resources and control services — v{version}
          </p>
        </div>
        <button
          onClick={() => queryClient.invalidateQueries({ queryKey: ['system-resources'] })}
          className="btn-secondary"
        >
          <RefreshCw className="w-4 h-4" />
          Refresh
        </button>
      </div>

      {/* Resource Usage Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {resourceCards.map((card, i) => {
          const Icon = card.icon;
          return (
            <motion.div
              key={card.label}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className="card p-5"
            >
              <div className="flex items-center gap-3 mb-4">
                <div
                  className="p-2.5 rounded-lg"
                  style={{ background: card.iconBg }}
                >
                  <Icon className="w-5 h-5" style={{ color: card.iconColor }} />
                </div>
                <div>
                  <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>{card.label}</p>
                  <p className="text-xl font-bold" style={{ color: 'var(--text-primary)' }}>{card.value}</p>
                </div>
              </div>

              <ProgressBar value={card.percent} color={getBarColor(card.percent)} />

              {card.detail && (
                <p className="text-xs mt-2" style={{ color: 'var(--text-tertiary)' }}>{card.detail}</p>
              )}
            </motion.div>
          );
        })}
      </div>

      {/* Service Controls */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="card p-5"
      >
        <h3 className="text-sm font-semibold mb-4" style={{ color: 'var(--text-primary)' }}>
          Service Controls
        </h3>

        <div className="space-y-3">
          {/* Queue Worker */}
          <div
            className="flex items-center justify-between p-3.5 rounded-lg"
            style={{ background: 'var(--bg-input)' }}
          >
            <div className="flex items-center gap-3">
              <Server className="w-4 h-4" style={{ color: 'var(--text-tertiary)' }} />
              <div>
                <p className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>
                  Queue Worker
                </p>
                <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>
                  Process pending messages in queue
                </p>
              </div>
            </div>

            <div className="flex gap-2">
              <button
                onClick={() => handleAction('start-queue', startQueueMutation)}
                disabled={actionLoading === 'start-queue'}
                className="text-xs py-1.5 px-3 rounded-lg flex items-center gap-1.5 font-medium transition-colors"
                style={{
                  background: 'var(--success-soft)',
                  color: 'var(--success)',
                  border: '1px solid var(--success-soft-border)',
                }}
              >
                {actionLoading === 'start-queue' ? (
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Play className="w-3.5 h-3.5" />
                )}
                Start
              </button>

              <button
                onClick={() => handleAction('stop-queue', stopQueueMutation)}
                disabled={actionLoading === 'stop-queue'}
                className="btn-danger text-xs py-1.5 px-3"
              >
                {actionLoading === 'stop-queue' ? (
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Square className="w-3.5 h-3.5" />
                )}
                Stop
              </button>
            </div>
          </div>

          {/* Baileys */}
          <div
            className="flex items-center justify-between p-3.5 rounded-lg"
            style={{ background: 'var(--bg-input)' }}
          >
            <div className="flex items-center gap-3">
              <Activity className="w-4 h-4" style={{ color: 'var(--text-tertiary)' }} />
              <div>
                <p className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>
                  Baileys Service
                </p>
                <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>
                  Restart WhatsApp Web connection
                </p>
              </div>
            </div>

            <button
              onClick={() => handleAction('restart-baileys', restartBaileysMutation)}
              disabled={actionLoading === 'restart-baileys'}
              className="btn-primary text-xs py-1.5 px-3"
            >
              {actionLoading === 'restart-baileys' ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <RefreshCw className="w-3.5 h-3.5" />
              )}
              Restart
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
