// dashboard-react/src/pages/Settings.tsx
import { useEffect, useState, useCallback, useRef } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import {
  Save,
  Loader2,
  Smartphone,
  Database,
  FileText,
} from 'lucide-react';
import { api } from '../services/api';
import { LoadingState } from '../components/ui/LoadingState';
import { toast } from 'sonner';

const DEFAULT_BAILEYS_URL = import.meta.env.VITE_BAILEYS_SERVER_URL || 'http://localhost:3001';
const DEFAULT_PROVIDER = 'baileys';
const DEFAULT_LOG_LEVEL = 'INFO';

function Toggle({ checked, onChange, label }: {
  checked: boolean;
  onChange: (val: boolean) => void;
  label: string;
}) {
  return (
    <label className="flex items-center gap-3 cursor-pointer">
      <button
        onClick={() => onChange(!checked)}
        className={`toggle ${checked ? 'active' : ''}`}
        role="switch"
        aria-checked={checked}
        aria-label={label}
        type="button"
      />
      <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>{label}</span>
    </label>
  );
}

export function Settings() {
  const queryClient = useQueryClient();
  const [formData, setFormData] = useState({
    whatsapp_provider: DEFAULT_PROVIDER,
    baileys_server_url: DEFAULT_BAILEYS_URL,
    baileys_enabled: true,
    log_level: DEFAULT_LOG_LEVEL,
    bds_file_path: '',
  });

  const { data: settings, isLoading } = useQuery({
    queryKey: ['settings'],
    queryFn: api.getSettingsConfig,
  });

  const hasInitializedRef = useRef(false);

  useEffect(() => {
    if (settings?.content && !hasInitializedRef.current) {
      hasInitializedRef.current = true;
      const content = settings.content as {
        whatsapp_provider?: string;
        baileys_server_url?: string;
        baileys_enabled?: boolean;
        log_level?: string;
        bds_file_path?: string;
      };
      setFormData({
        whatsapp_provider: content.whatsapp_provider || DEFAULT_PROVIDER,
        baileys_server_url: content.baileys_server_url || DEFAULT_BAILEYS_URL,
        baileys_enabled: content.baileys_enabled ?? true,
        log_level: content.log_level || DEFAULT_LOG_LEVEL,
        bds_file_path: content.bds_file_path || '',
      });
    }
  }, [settings]);

  const updateMutation = useMutation({
    mutationFn: api.updateSettingsConfig,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['settings'] });
      toast.success('Settings saved successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to save settings: ${error.message}`);
    },
  });

  const handleSubmit = useCallback(async (e: React.FormEvent) => {
    e.preventDefault();
    await updateMutation.mutateAsync(formData);
  }, [updateMutation, formData]);

  if (isLoading) {
    return <LoadingState size="lg" fullPage />;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>Settings</h2>
        <p className="text-sm mt-1" style={{ color: 'var(--text-tertiary)' }}>
          Configure application settings
        </p>
      </div>

      {/* Settings Form */}
      <motion.form
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        onSubmit={handleSubmit}
        className="card p-6"
      >
        <div className="space-y-8">
          {/* WhatsApp Settings */}
          <div
            className="pb-6 border-b"
            style={{ borderColor: 'var(--border-default)' }}
          >
            <div className="flex items-center gap-2.5 mb-4">
              <div
                className="p-2 rounded-lg"
                style={{ background: 'var(--brand-soft)', border: '1px solid var(--brand-soft-border)' }}
              >
                <Smartphone className="w-4 h-4" style={{ color: 'var(--brand-accent)' }} />
              </div>
              <h3 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
                WhatsApp Settings
              </h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>
                  Provider
                </label>
                <select
                  value={formData.whatsapp_provider}
                  onChange={(e) => setFormData({ ...formData, whatsapp_provider: e.target.value })}
                  className="input"
                >
                  <option value="baileys">Baileys</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>
                  Baileys Server URL
                </label>
                <input
                  type="text"
                  value={formData.baileys_server_url}
                  onChange={(e) => setFormData({ ...formData, baileys_server_url: e.target.value })}
                  className="input"
                />
              </div>
            </div>

            <div className="mt-4">
              <Toggle
                checked={formData.baileys_enabled}
                onChange={(val) => setFormData({ ...formData, baileys_enabled: val })}
                label="Enable Baileys Integration"
              />
            </div>
          </div>

          {/* Database Settings */}
          <div
            className="pb-6 border-b"
            style={{ borderColor: 'var(--border-default)' }}
          >
            <div className="flex items-center gap-2.5 mb-4">
              <div
                className="p-2 rounded-lg"
                style={{ background: 'var(--info-soft)', border: '1px solid var(--info-soft-border)' }}
              >
                <Database className="w-4 h-4" style={{ color: 'var(--info)' }} />
              </div>
              <h3 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
                Database Settings
              </h3>
            </div>

            <div>
              <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>
                Busy Database File Path
              </label>
              <input
                type="text"
                value={formData.bds_file_path}
                onChange={(e) => setFormData({ ...formData, bds_file_path: e.target.value })}
                placeholder="C:\\Path\\To\\Your\\Database.bds"
                className="input"
              />
              <p className="text-xs mt-1.5" style={{ color: 'var(--text-tertiary)' }}>
                Path to the Busy .bds database file
              </p>
            </div>
          </div>

          {/* Logging Settings */}
          <div>
            <div className="flex items-center gap-2.5 mb-4">
              <div
                className="p-2 rounded-lg"
                style={{ background: 'var(--warning-soft)', border: '1px solid var(--warning-soft-border)' }}
              >
                <FileText className="w-4 h-4" style={{ color: 'var(--warning)' }} />
              </div>
              <h3 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
                Logging Settings
              </h3>
            </div>

            <div>
              <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>
                Log Level
              </label>
              <select
                value={formData.log_level}
                onChange={(e) => setFormData({ ...formData, log_level: e.target.value })}
                className="input max-w-xs"
              >
                <option value="DEBUG">Debug</option>
                <option value="INFO">Info</option>
                <option value="WARNING">Warning</option>
                <option value="ERROR">Error</option>
              </select>
            </div>
          </div>
        </div>

        {/* Submit Button */}
        <div className="mt-8 flex justify-end">
          <button
            type="submit"
            disabled={updateMutation.isPending}
            className="btn-primary"
          >
            {updateMutation.isPending ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Saving...
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                Save Settings
              </>
            )}
          </button>
        </div>
      </motion.form>
    </div>
  );
}

// dashboard/src/views/Settings.vue
<template>
  <div class="page-container">
    <div class="page-head">
      <h1>Settings</h1>
      <div class="nav-links">
        <router-link to="/" class="nav-link">Overview</router-link>
        <router-link to="/whatsapp" class="nav-link">WhatsApp</router-link>
        <router-link to="/system" class="nav-link">System Control</router-link>
      </div>
    </div>

    <Card>
      <template #title>Configuration (conf.json)</template>
      <template #content>
        <div class="form-grid">
          <label>
            WhatsApp Provider
            <select v-model="form.whatsapp_provider">
              <option value="baileys">baileys</option>
              <option value="meta">meta</option>
              <option value="webhook">webhook</option>
              <option value="evolution">evolution</option>
            </select>
          </label>

          <label>
            Baileys Server URL
            <input v-model="form.baileys_server_url" type="text" placeholder="http://localhost:3001" />
          </label>

          <label>
            Log Level
            <select v-model="form.log_level">
              <option value="DEBUG">DEBUG</option>
              <option value="INFO">INFO</option>
              <option value="WARNING">WARNING</option>
              <option value="ERROR">ERROR</option>
              <option value="CRITICAL">CRITICAL</option>
            </select>
          </label>

          <label>
            BDS File Path
            <input v-model="form.bds_file_path" type="text" placeholder="C:\\Path\\db12025.bds" />
          </label>

          <label class="switch">
            <input v-model="form.baileys_enabled" type="checkbox" />
            Enable Baileys
          </label>
        </div>

        <div class="actions">
          <Button icon="pi pi-refresh" label="Reload" severity="secondary" :loading="loading" @click="loadSettings" />
          <Button icon="pi pi-save" label="Save Settings" :loading="saving" @click="saveSettings" />
        </div>

        <p class="note">
          Changes are persisted to `conf.json`. Some changes require restart to fully apply.
        </p>
        <p v-if="message" class="message">{{ message }}</p>
      </template>
    </Card>

    <Card>
      <template #title>Current Runtime Values</template>
      <template #content>
        <pre class="runtime">{{ runtimeSettingsPretty }}</pre>
      </template>
    </Card>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from '@/services/api'
import Card from 'primevue/card'
import Button from 'primevue/button'

const loading = ref(false)
const saving = ref(false)
const message = ref('')
const runtimeSettings = ref<Record<string, any>>({})

const form = reactive({
  whatsapp_provider: 'baileys',
  baileys_server_url: 'http://localhost:3001',
  baileys_enabled: true,
  log_level: 'INFO',
  bds_file_path: '',
})

const runtimeSettingsPretty = computed(() => JSON.stringify(runtimeSettings.value, null, 2))

const loadSettings = async () => {
  loading.value = true
  message.value = ''
  try {
    const [runtime, config] = await Promise.all([
      api.getSettings(),
      api.getSettingsConfig(),
    ])
    runtimeSettings.value = runtime
    const content = config.content || {}
    form.whatsapp_provider = content.whatsapp?.provider || runtime.WHATSAPP_PROVIDER || form.whatsapp_provider
    form.baileys_server_url = content.baileys?.server_url || runtime.BAILEYS_SERVER_URL || form.baileys_server_url
    form.baileys_enabled = Boolean(content.baileys?.enabled ?? runtime.BAILEYS_ENABLED)
    form.log_level = content.logging?.level || runtime.LOG_LEVEL || form.log_level
    form.bds_file_path = content.database?.bds_file_path || ''
  } catch (error) {
    console.error('Failed to load settings', error)
    message.value = 'Failed to load settings.'
  } finally {
    loading.value = false
  }
}

const saveSettings = async () => {
  saving.value = true
  message.value = ''
  try {
    const result = await api.updateSettingsConfig({
      whatsapp_provider: form.whatsapp_provider,
      baileys_server_url: form.baileys_server_url,
      baileys_enabled: form.baileys_enabled,
      log_level: form.log_level,
      bds_file_path: form.bds_file_path,
    })
    message.value = result.message || 'Settings saved.'
    await loadSettings()
  } catch (error: any) {
    console.error('Failed to save settings', error)
    message.value = error?.message || 'Failed to save settings.'
  } finally {
    saving.value = false
  }
}

onMounted(loadSettings)
</script>

<style scoped>
.page-container {
  max-width: 1400px;
  margin: 0 auto;
  display: grid;
  gap: 1rem;
}

.page-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
}

.nav-links {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
}

.nav-link {
  padding: 0.25rem 0.6rem;
  border: 1px solid var(--surface-border);
  border-radius: 999px;
  text-decoration: none;
  color: var(--text-color-secondary);
  font-size: 0.75rem;
}

.form-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 0.9rem;
}

label {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  font-size: 0.8rem;
  color: var(--text-color-secondary);
}

select,
input[type="text"] {
  border: 1px solid var(--surface-border);
  border-radius: 6px;
  background: var(--surface-card);
  color: var(--text-color);
  padding: 0.45rem 0.55rem;
}

.switch {
  flex-direction: row;
  align-items: center;
  margin-top: 1.45rem;
  color: var(--text-color);
}

.actions {
  display: flex;
  gap: 0.6rem;
  margin-top: 1rem;
}

.note,
.message {
  margin-top: 0.8rem;
  color: var(--text-color-secondary);
}

.runtime {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
  font-size: 0.82rem;
}
</style>
