// dashboard-react/src/pages/WhatsAppManager.tsx
import { useEffect, useState, useCallback } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import {
  RefreshCw,
  LogOut,
  QrCode,
  CheckCircle,
  XCircle,
  Smartphone,
  AlertTriangle,
  Loader2,
} from 'lucide-react';
import { api } from '../services/api';
import { useSystemStore } from '../stores/systemStore';
import { LoadingState } from '../components/ui/LoadingState';
import { getStatusStyle } from '../utils/statusColors';
import { REFETCH_INTERVALS } from '../constants';
import { toast } from 'sonner';

export function WhatsAppManager() {
  const queryClient = useQueryClient();
  const setBaileysStatus = useSystemStore((state) => state.setBaileysStatus);
  const [isRefreshing, setIsRefreshing] = useState(false);

  const { data: status, isLoading } = useQuery({
    queryKey: ['baileys-status'],
    queryFn: () => api.getBaileysStatus(),
    refetchInterval: REFETCH_INTERVALS.BAILEYS_STATUS,
  });

  const { data: qrData, isLoading: isLoadingQr } = useQuery({
    queryKey: ['baileys-qr', status?.state, status?.qrAvailable],
    queryFn: () => api.getBaileysQr(),
    enabled: status?.state === 'qr_ready' || status?.qrAvailable === true,
    refetchInterval: (query) => {
      const data = query.state.data;
      if (data?.data?.state === 'connected') return false;
      return 3000;
    },
  });

  useEffect(() => {
    if (status) {
      setBaileysStatus(status);
    }
  }, [status, setBaileysStatus]);

  const restartMutation = useMutation({
    mutationFn: () => api.restartBaileys(),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['baileys-status'] });
      queryClient.invalidateQueries({ queryKey: ['baileys-qr'] });
      toast.success('Baileys service restarted successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to restart Baileys: ${error.message}`);
    },
  });

  const disconnectMutation = useMutation({
    mutationFn: () => api.disconnectWhatsApp(),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['baileys-status'] });
      queryClient.invalidateQueries({ queryKey: ['baileys-qr'] });
      toast.success('WhatsApp disconnected successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to disconnect WhatsApp: ${error.message}`);
    },
  });

  const clearSessionMutation = useMutation({
    mutationFn: () => api.clearWhatsAppSession(),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['baileys-status'] });
      queryClient.invalidateQueries({ queryKey: ['baileys-qr'] });
      toast.success('Session cleared successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to clear session: ${error.message}`);
    },
  });

  const handleRefresh = useCallback(async () => {
    setIsRefreshing(true);
    await queryClient.invalidateQueries({ queryKey: ['baileys-status'] });
    await queryClient.invalidateQueries({ queryKey: ['baileys-qr'] });
    setIsRefreshing(false);
  }, [queryClient]);

  const getStatusIcon = (state: string) => {
    switch (state) {
      case 'connected':
        return <CheckCircle className="w-5 h-5" />;
      case 'qr_ready':
        return <QrCode className="w-5 h-5" />;
      case 'connecting':
      case 'reconnecting':
        return <Loader2 className="w-5 h-5 animate-spin" />;
      default:
        return <XCircle className="w-5 h-5" />;
    }
  };

  if (isLoading) {
    return <LoadingState size="lg" fullPage />;
  }

  const isConnected = status?.state === 'connected';
  const isQrReady = status?.state === 'qr_ready' || status?.qrAvailable === true;
  const statusStyle = getStatusStyle(status?.state || 'unknown');

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>
            WhatsApp
          </h2>
          <p className="text-sm mt-0.5" style={{ color: 'var(--text-tertiary)' }}>
            Manage connection and session
          </p>
        </div>
        <button onClick={handleRefresh} disabled={isRefreshing} className="btn-secondary">
          <RefreshCw className={`w-4 h-4 ${isRefreshing && 'animate-spin'}`} />
          Refresh
        </button>
      </div>

      {/* Status Card */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        className="card p-5"
      >
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-4">
            <div
              className="p-3 rounded-xl"
              style={{ background: statusStyle.bg, color: statusStyle.color, border: `1px solid ${statusStyle.border}` }}
            >
              {getStatusIcon(status?.state || 'unknown')}
            </div>

            <div>
              <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>Connection Status</p>
              <p className="text-xl font-bold capitalize" style={{ color: 'var(--text-primary)' }}>
                {(status?.state || 'unknown').replace('_', ' ')}
              </p>
            </div>
          </div>

          <div className="flex gap-2">
            <button
              onClick={() => restartMutation.mutate()}
              disabled={restartMutation.isPending}
              className="btn-primary"
            >
              {restartMutation.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <RefreshCw className="w-4 h-4" />
              )}
              Restart
            </button>

            {isConnected && (
              <button
                onClick={() => disconnectMutation.mutate()}
                disabled={disconnectMutation.isPending}
                className="btn-danger"
              >
                {disconnectMutation.isPending ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <LogOut className="w-4 h-4" />
                )}
                Disconnect
              </button>
            )}
          </div>
        </div>

        {status?.error && (
          <div
            className="p-3 rounded-lg flex items-start gap-2.5"
            style={{
              background: 'var(--danger-soft)',
              border: '1px solid var(--danger-soft-border)',
            }}
          >
            <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" style={{ color: 'var(--danger)' }} />
            <p className="text-sm" style={{ color: 'var(--danger)' }}>{status.error}</p>
          </div>
        )}

        {isConnected && status?.user && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-5">
            <div className="p-3 rounded-lg" style={{ background: 'var(--bg-input)' }}>
              <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>Connected Account</p>
              <p className="text-sm font-medium mt-0.5" style={{ color: 'var(--text-primary)' }}>
                {status.user.name}
              </p>
            </div>
            <div className="p-3 rounded-lg" style={{ background: 'var(--bg-input)' }}>
              <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>Phone Number</p>
              <p className="text-sm font-medium mt-0.5" style={{ color: 'var(--text-primary)' }}>
                {status.user.phone}
              </p>
            </div>
          </div>
        )}
      </motion.div>

      {/* QR Code Section */}
      {isQrReady && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="card p-8"
        >
          <div className="text-center">
            <div
              className="inline-flex items-center justify-center w-14 h-14 rounded-full mb-4"
              style={{ background: 'var(--warning-soft)' }}
            >
              <QrCode className="w-7 h-7" style={{ color: 'var(--warning)' }} />
            </div>

            <h3 className="text-lg font-semibold mb-1.5" style={{ color: 'var(--text-primary)' }}>
              Scan QR Code
            </h3>
            <p className="text-sm mb-6 max-w-md mx-auto" style={{ color: 'var(--text-tertiary)' }}>
              Open WhatsApp on your phone, go to Settings &gt; Linked Devices, and scan this QR code to connect
            </p>

            <div className="inline-block p-5 bg-white rounded-xl shadow-lg">
              {isLoadingQr ? (
                <div className="w-56 h-56 flex items-center justify-center">
                  <Loader2 className="w-8 h-8 animate-spin" style={{ color: 'var(--text-tertiary)' }} />
                </div>
              ) : qrData?.data?.qrImage ? (
                <img
                  src={qrData.data.qrImage}
                  alt="WhatsApp QR Code"
                  className="w-56 h-56"
                />
              ) : (
                <div className="w-56 h-56 flex items-center justify-center text-center p-4">
                  <p className="text-sm" style={{ color: 'var(--text-tertiary)' }}>
                    QR code not available yet. Please wait...
                  </p>
                </div>
              )}
            </div>
          </div>
        </motion.div>
      )}

      {/* Session Management */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15 }}
        className="card p-5"
      >
        <h3 className="text-sm font-semibold mb-4" style={{ color: 'var(--text-primary)' }}>
          Session Management
        </h3>

        <div
          className="flex items-center justify-between p-3.5 rounded-lg"
          style={{ background: 'var(--bg-input)' }}
        >
          <div className="flex items-center gap-3">
            <Smartphone className="w-4 h-4" style={{ color: 'var(--text-tertiary)' }} />
            <div>
              <p className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>
                Clear Session Data
              </p>
              <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>
                Remove saved credentials and require re-authentication
              </p>
            </div>
          </div>

          <button
            onClick={() => clearSessionMutation.mutate()}
            disabled={clearSessionMutation.isPending}
            className="btn-danger text-xs"
          >
            {clearSessionMutation.isPending ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              'Clear Session'
            )}
          </button>
        </div>
      </motion.div>
    </div>
  );
}

// dashboard/src/views/WhatsAppManager.vue
<template>
  <div class="bw-page">
    <div class="bw-page-header">
      <div>
        <h1>WhatsApp Connection</h1>
        <p class="subtitle">Manage your WhatsApp Web session via Baileys</p>
      </div>
      <div class="header-actions">
        <Button label="Refresh" icon="pi pi-refresh" class="p-button-outlined p-button-sm" :loading="loading" @click="refresh" />
        <Button label="Restart" icon="pi pi-replay" severity="warning" class="p-button-outlined p-button-sm" :loading="busyRestart" @click="restartConnection" />
        <Button label="Logout" icon="pi pi-sign-out" severity="danger" class="p-button-outlined p-button-sm" :loading="busyLogout" @click="logoutConnection" />
      </div>
    </div>

    <div class="wa-grid">
      <!-- Status Card -->
      <div class="bw-section">
        <div class="bw-section-header">
          <h2><i class="pi pi-info-circle"></i> Connection Status</h2>
          <Tag :value="statusLabel" :severity="statusSeverity" />
        </div>
        <div class="bw-section-body">
          <div class="kv-list">
            <div class="kv-row">
              <span class="kv-label">Provider</span>
              <span class="kv-value">Baileys (WhatsApp Web)</span>
            </div>
            <div class="kv-row">
              <span class="kv-label">State</span>
              <span class="kv-value">
                <span class="bw-status-dot" :class="status?.state === 'connected' ? 'bw-status-dot--online' : 'bw-status-dot--offline'" style="margin-right: 6px"></span>
                {{ status?.state || 'unknown' }}
              </span>
            </div>
            <div class="kv-row">
              <span class="kv-label">Phone</span>
              <span class="kv-value">{{ userPhone }}</span>
            </div>
            <div class="kv-row">
              <span class="kv-label">Name</span>
              <span class="kv-value">{{ userName }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- QR Card -->
      <div class="bw-section qr-section">
        <div class="bw-section-header">
          <h2><i class="pi pi-qrcode"></i> QR Scan</h2>
        </div>
        <div class="bw-section-body qr-body">
          <!-- Connected -->
          <div v-if="status?.state === 'connected'" class="qr-connected">
            <div class="connected-icon">
              <i class="pi pi-check-circle"></i>
            </div>
            <p>WhatsApp is connected</p>
            <small>No QR scan required</small>
          </div>

          <!-- QR Available -->
          <div v-else-if="qrImage" class="qr-available">
            <div class="qr-image-wrap">
              <img :src="qrImage" alt="WhatsApp QR Code" class="qr-img" />
            </div>
            <div class="qr-steps">
              <div class="qr-step"><span class="step-num">1</span> Open WhatsApp on phone</div>
              <div class="qr-step"><span class="step-num">2</span> Settings → Linked Devices</div>
              <div class="qr-step"><span class="step-num">3</span> Tap "Link a Device" and scan</div>
            </div>
          </div>

          <!-- Waiting -->
          <div v-else class="qr-waiting">
            <i class="pi pi-spin pi-spinner" style="font-size: 1.5rem; color: var(--bw-brand-primary)"></i>
            <p>Waiting for QR code...</p>
            <small>Make sure Baileys server is running</small>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import Button from 'primevue/button'
import Tag from 'primevue/tag'
import { api } from '@/services/api'
import { useSystemStore } from '@/stores/system'
import type { BaileysStatus } from '@/types'

const systemStore = useSystemStore()
const loading = ref(false)
const busyRestart = ref(false)
const busyLogout = ref(false)
const status = ref<BaileysStatus | null>(null)
const qrImage = ref<string>('')
let timer: number | null = null

const statusLabel = computed(() => {
  const state = status.value?.state
  if (state === 'connected') return 'Connected'
  if (state === 'qr_ready' || state === 'logged_out') return 'Scan Required'
  if (state === 'connecting' || state === 'reconnecting') return 'Connecting'
  if (state === 'disconnected') return 'Disconnected'
  return 'Unknown'
})

const statusSeverity = computed(() => {
  const state = status.value?.state
  if (state === 'connected') return 'success'
  if (state === 'qr_ready' || state === 'logged_out' || state === 'connecting' || state === 'reconnecting') return 'warning'
  return 'danger'
})

const userPhone = computed(() => {
  const id = status.value?.user?.id || ''
  return id ? id.split(':')[0] : 'Not connected'
})

const userName = computed(() => status.value?.user?.name || 'Not connected')

const refresh = async () => {
  loading.value = true
  try {
    const latestStatus = await api.getBaileysStatus()
    status.value = latestStatus
    systemStore.setBaileysStatus(latestStatus)
    if (latestStatus.state !== 'connected') {
      const qr = await api.getBaileysQr()
      qrImage.value = qr.qrImage || ''
    } else {
      qrImage.value = ''
    }
  } catch (error) {
    status.value = { state: 'unreachable', error: error instanceof Error ? error.message : String(error) }
    qrImage.value = ''
  } finally {
    loading.value = false
  }
}

const restartConnection = async () => {
  busyRestart.value = true
  try { await api.restartBaileys(); await refresh() } finally { busyRestart.value = false }
}

const logoutConnection = async () => {
  busyLogout.value = true
  try { await api.disconnectWhatsApp(); await refresh() } finally { busyLogout.value = false }
}

onMounted(async () => {
  await refresh()
  timer = window.setInterval(refresh, 5000)
})

onBeforeUnmount(() => { if (timer) clearInterval(timer) })
</script>

<style scoped>
.header-actions {
  display: flex;
  gap: var(--bw-space-sm);
  flex-wrap: wrap;
}

.wa-grid {
  display: grid;
  grid-template-columns: 1fr 1.3fr;
  gap: var(--bw-space-lg);
}

@media (max-width: 960px) {
  .wa-grid { grid-template-columns: 1fr; }
}

/* KV list */
.kv-list {
  display: flex;
  flex-direction: column;
}

.kv-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.7rem 0;
  border-bottom: 1px solid var(--bw-border-subtle);
}

.kv-row:last-child { border-bottom: none; }

.kv-label {
  font-size: 0.82rem;
  color: var(--bw-text-muted);
}

.kv-value {
  font-weight: 600;
  font-size: 0.875rem;
  display: flex;
  align-items: center;
}

/* QR states */
.qr-body {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 320px;
}

.qr-connected {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--bw-space-sm);
  color: var(--bw-text-secondary);
}

.connected-icon {
  width: 64px;
  height: 64px;
  border-radius: 50%;
  background: rgba(34, 197, 94, 0.12);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: var(--bw-space-sm);
}

.connected-icon i {
  font-size: 2rem;
  color: #22c55e;
}

.qr-available {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--bw-space-lg);
  width: 100%;
}

.qr-image-wrap {
  padding: 1rem;
  background: white;
  border-radius: var(--bw-radius-lg);
  box-shadow: var(--bw-shadow-md);
}

.qr-img {
  width: 260px;
  max-width: 100%;
  display: block;
}

.qr-steps {
  display: flex;
  flex-direction: column;
  gap: var(--bw-space-sm);
  width: 100%;
  max-width: 300px;
}

.qr-step {
  display: flex;
  align-items: center;
  gap: var(--bw-space-sm);
  font-size: 0.82rem;
  color: var(--bw-text-secondary);
}

.step-num {
  width: 22px;
  height: 22px;
  border-radius: 50%;
  background: var(--bw-brand-primary-alpha);
  color: var(--bw-brand-primary-light);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.7rem;
  font-weight: 700;
  flex-shrink: 0;
}

.qr-waiting {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--bw-space-sm);
  color: var(--bw-text-muted);
}
</style>
